version: "3"
services:
  backend:
    build: ./server
    command: "npm start"
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./client
    command: "npm start"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    command: mongod 

